"""Stable, side-effect-free public API for the K0 grounding state kernel."""

from valibra_agent.requirement_grounding.models import (
    Ambiguity,
    Candidate,
    Error,
    Evidence,
    GroundedAmbiguityHypothesis,
    GroundingEvidence,
    GroundingSlot,
    InterpretationCandidate,
    Metrics,
    Observation,
    OperationSlot,
    Patch,
    PendingToolCall,
    PhaseTransition,
    RequirementFrame,
    RequirementGroundingPatch,
    RequirementGroundingRuntime,
    RequirementGroundingState,
    Runtime,
    RuntimeMetrics,
    SCHEMA_VERSION,
    SQLImpact,
    SchemaSlot,
    State,
    ValibraError,
    ValueSlot,
)
from valibra_agent.requirement_grounding.linguistic_hints import (
    LinguisticHint,
    extract_linguistic_hints,
    normalize_linguistic_text,
)
from valibra_agent.requirement_grounding.observations import (
    ObservationNormalizationError,
    build_observation,
    canonical_json,
    stable_digest,
)
from valibra_agent.requirement_grounding.prompt_view import render_prompt_view
from valibra_agent.requirement_grounding.reducer import (
    ReductionError,
    apply_patch,
    validate_runtime,
)
from valibra_agent.requirement_grounding.service import (
    GroundingControlError,
    GroundingServiceResult,
    add_pending_tool_call,
    process_observation,
    process_phase_transition,
    remove_pending_tool_call,
)
from valibra_agent.requirement_grounding.telemetry import (
    increment_metrics,
    record_failure,
    set_last_error,
)
from valibra_agent.requirement_grounding.updater import (
    NoOpUpdater,
    RuleUpdater,
    build_noop_patch,
    build_rule_patch,
)

__all__ = [
    "Ambiguity",
    "Candidate",
    "Error",
    "Evidence",
    "GroundedAmbiguityHypothesis",
    "GroundingEvidence",
    "GroundingControlError",
    "GroundingServiceResult",
    "GroundingSlot",
    "InterpretationCandidate",
    "LinguisticHint",
    "Metrics",
    "NoOpUpdater",
    "Observation",
    "ObservationNormalizationError",
    "OperationSlot",
    "Patch",
    "PendingToolCall",
    "PhaseTransition",
    "ReductionError",
    "RequirementFrame",
    "RequirementGroundingPatch",
    "RequirementGroundingRuntime",
    "RequirementGroundingState",
    "Runtime",
    "RuntimeMetrics",
    "RuleUpdater",
    "SCHEMA_VERSION",
    "SQLImpact",
    "SchemaSlot",
    "State",
    "ValibraError",
    "ValueSlot",
    "apply_patch",
    "add_pending_tool_call",
    "build_noop_patch",
    "build_rule_patch",
    "build_observation",
    "canonical_json",
    "increment_metrics",
    "extract_linguistic_hints",
    "normalize_linguistic_text",
    "process_observation",
    "process_phase_transition",
    "record_failure",
    "render_prompt_view",
    "remove_pending_tool_call",
    "set_last_error",
    "stable_digest",
    "validate_runtime",
]
